/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/utils/hub.py:106: FutureWarning: Using `PYTORCH_PRETRAINED_BERT_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/utils/hub.py:106: FutureWarning: Using `PYTORCH_TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/utils/hub.py:106: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/storage/weinig/cdl-inflation-narrative/annotation/labelstudio/agreement.py:222: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['label'] = train['label'].replace(self.label2id_map)
/storage/weinig/cdl-inflation-narrative/annotation/labelstudio/agreement.py:223: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  valid['label'] = valid['label'].replace(self.label2id_map)
/storage/weinig/cdl-inflation-narrative/annotation/labelstudio/agreement.py:224: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['label'] = test['label'].replace(self.label2id_map)
/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py:561: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at worldbank/econberta and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
annotator 5: 0 document(s) to annotate.
annotator 7: 0 document(s) to annotate.
annotator 8: 0 document(s) to annotate.
annotator 9: 0 document(s) to annotate.
inner_id_list 488, annotator_5: 488
Updated annotation from user 5, result saved in ./export/task_1_annotation.csv
Task 1 (User 5 - Sviatoslav)
inner_id_list 488, annotator_7: 488
Updated annotation from user 7, result saved in ./export/task_1_annotation.csv
Task 1 (User 6 - Julia)
inner_id_list 488, annotator_8: 488
Updated annotation from user 8, result saved in ./export/task_1_annotation.csv
Task 1 (User 7 - Darian)
inner_id_list 488, annotator_9: 488
Updated annotation from user 9, result saved in ./export/task_1_annotation.csv
Task 1 (User 8 - Kim)
has winner ratio: 0.8790983606557377
all agreeing count: 232
0.6858854912630578
Map:   0%|          | 0/341 [00:00<?, ? examples/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Map: 100%|██████████| 341/341 [00:00<00:00, 449.17 examples/s]Map: 100%|██████████| 341/341 [00:00<00:00, 444.91 examples/s]
Map:   0%|          | 0/49 [00:00<?, ? examples/s]Map: 100%|██████████| 49/49 [00:00<00:00, 471.97 examples/s]Map: 100%|██████████| 49/49 [00:00<00:00, 466.03 examples/s]
Map:   0%|          | 0/98 [00:00<?, ? examples/s]Map: 100%|██████████| 98/98 [00:00<00:00, 465.68 examples/s]Map: 100%|██████████| 98/98 [00:00<00:00, 462.32 examples/s]
  0%|          | 0/440 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/storage/weinig/cdl-inflation-narrative/annotation/labelstudio/agreement.py", line 315, in <module>
    inflation_narrative.train_sequence_classifier()
  File "/storage/weinig/cdl-inflation-narrative/annotation/labelstudio/agreement.py", line 280, in train_sequence_classifier
    trainer.train()
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/trainer.py", line 2241, in train
    return inner_training_loop(
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/trainer.py", line 2548, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/trainer.py", line 3698, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/trainer.py", line 3759, in compute_loss
    outputs = model(**inputs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 193, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 212, in parallel_apply
    return parallel_apply(
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 126, in parallel_apply
    output.reraise()
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/_utils.py", line 733, in reraise
    raise exception
torch.OutOfMemoryError: Caught OutOfMemoryError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 96, in _worker
    output = module(*input, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 1175, in forward
    outputs = self.deberta(
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 870, in forward
    encoder_outputs = self.encoder(
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 674, in forward
    output_states, attn_weights = layer_module(
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 442, in forward
    attention_output, att_matrix = self.attention(
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 375, in forward
    self_output, att_matrix = self.self(
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 255, in forward
    rel_att = self.disentangled_attention_bias(
  File "/storage/weinig/anaconda3/envs/cdl/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 353, in disentangled_attention_bias
    score += p2c_att / scale.to(dtype=p2c_att.dtype)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.83 GiB. GPU 0 has a total capacity of 47.40 GiB of which 971.31 MiB is free. Including non-PyTorch memory, this process has 46.45 GiB memory in use. Of the allocated memory 45.66 GiB is allocated by PyTorch, and 322.53 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

  0%|          | 0/440 [00:01<?, ?it/s]
